[mypy]
python_version = 3.12
strict = true
ignore_missing_imports = true
warn_unused_ignores = false

[mypy-whaledecode.adapters.*]
ignore_errors = true

[mypy-whaledecode.jobs.*]
ignore_errors = true

[mypy-whaledecode.entrypoints.*]
ignore_errors = true
