[mypy]
python_version = 3.11
strict = true
ignore_missing_imports = true
warn_unused_ignores = false

[mypy-whaleagent.adapters.*]
ignore_errors = true

[mypy-whaleagent.jobs.*]
ignore_errors = true

[mypy-whaleagent.entrypoints.*]
ignore_errors = true
