from typing import Any, Protocol


class Repository(Protocol):
    async def create(self, entity: Any) -> Any: ...

    async def get(self, id: int) -> Any | None: ...

    async def update(self, entity: Any) -> None: ...

    async def delete(self, id: int) -> None: ...


class UserRepository(Protocol):
    async def get_by_tg_id(self, tg_id: int) -> Any | None: ...

    async def create(self, user: Any) -> Any: ...

    async def update(self, user: Any) -> None: ...

    async def list_by_plan(self, plan: str) -> list[Any]: ...


class CuratedWalletRepository(Protocol):
    async def list_active(self, chain: str | None = None) -> list[Any]: ...

    async def search_by_label(self, query: str) -> list[Any]: ...

    async def create(self, wallet: Any) -> Any: ...

    async def get(self, id: int) -> Any | None: ...


class TrackedWalletRepository(Protocol):
    async def list_by_user(self, user_id: int) -> list[Any]: ...

    async def create(self, wallet: Any) -> Any: ...

    async def deactivate(self, id: int) -> None: ...

    async def count_active_by_user(self, user_id: int) -> int: ...


class CandidateEventRepository(Protocol):
    async def create(self, event: Any) -> Any: ...

    async def get_by_dedupe_key(self, dedupe_key: str) -> Any | None: ...

    async def list_by_status(self, status: str, limit: int = 100) -> list[Any]: ...


class AlertRepository(Protocol):
    async def create(self, alert: Any) -> Any: ...

    async def get_by_dedupe_key(self, dedupe_key: str) -> Any | None: ...

    async def list_by_user(self, user_id: int, limit: int = 50) -> list[Any]: ...

    async def list_by_status(self, status: str, limit: int = 100) -> list[Any]: ...


class AgentRunRepository(Protocol):
    async def create(self, run: Any) -> Any: ...

    async def update(self, run: Any) -> None: ...

    async def list_recent(self, limit: int = 20) -> list[Any]: ...


class BriefingRepository(Protocol):
    async def create(self, briefing: Any) -> Any: ...

    async def get_by_user_and_date(self, user_id: int, date: str) -> Any | None: ...


class AdminAuditLogRepository(Protocol):
    async def create(self, log_entry: Any) -> Any: ...
